koji-build-scratch.sh: tag rawhide should now be built

diff --git a/scripts/koji-build-scratch.sh.in b/scripts/koji-build-scratch.sh.in
--- a/scripts/koji-build-scratch.sh.in
+++ b/scripts/koji-build-scratch.sh.in
@@ -65,6 +65,12 @@ TARGETS=${TARGETS:-"$FEDORA_CURRENT_RELEASE_TAGS $EPEL_CURRENT_RELEASE_TAGS"}
 
 for t in $TARGETS; do
 #    echo "koji build --scratch $t$_SUFFIX $srpm"
-    koji build --scratch "$t$_SUFFIX" "$srpm"
+    if [ ! "$t" = "rawhide" ]; then
+	t=$t$_SUFFIX
+    fi
+    if ! koji build --scratch "$t" "$srpm"; then
+	echo "Koji build failed on $t" > /dev/stderr
+	exit 1
+    fi
 done
 
